package com.renturapp.scansist.Model;

public class GetCCGoodsModel {
    public Integer gRowNum;
    public Integer cCGoodID;
    public Integer cCRequestID;
    public Integer companyID;
    public Integer accountID;
    public Integer cCGoodQuantity;
    public Integer cCGoodLength;
    public Integer cCGoodWidth;
    public Integer cCGoodHeight;
    String cCGoodShippingMarks;
    String cCGoodCountryOrigin;
    Integer cCGoodRackID;
    Integer cCGoodPickListID;
    Boolean cCGoodAllocated;
    Object pickListDescription;
    public String rackDescription;
    String cCGoodCountryDispatch;
    String cCGoodDestination;
    String cCGoodCode;
    public String cCGoodDescription;
    String cCRequestValueCurrency;
    String cCRequestFreightCurrency;
    String cCRequestInsuranceCurrency;
    public Double cCGoodValue;
    Integer cCGoodFreightCost;
    Integer cCGoodInsuranceCost;
    public String cCGoodPackagingType;
    Integer cCGoodNetWeight;
    public Double cCGoodGrossWeight;
    String cCGoodDeclaration;
    String cCGoodTMRNumber;
    Boolean cCGoodIsLicensable;
    String cCGoodBarcode;
    Object cCGoodStatus;
    public String buyerStreet;
    public String sellerStreet;
    Integer getType;
    Object postType;
    Object putType;
    Integer uKCommCodeID;
}
